[package]
name = "jsonld-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "Command line interface for JSON-LD"
readme = "README.md"

[features]
default = []
ahash = ["jsonld/ahash"]
gxhash = ["jsonld/gxhash"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
contextual = "0.1.6"
iri-rs = { version = "3.3.4", features = ["static"] }
jsonld = { workspace = true, features = ["reqwest"] }
log = "0.4.29"
rdf-rs = { git = "ssh://git@github.com/mskvarc/rdf-rs.git" }
stderrlog = "0.6.0"
tokio = { version = "1.52.1", features = ["rt-multi-thread", "net", "macros"] }
