[package]
name = "jsonld-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "Command line interface for JSON-LD"
readme.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = []
ahash = ["jsonld/ahash"]
gxhash = ["jsonld/gxhash"]

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
contextual = "0.1.6"
iri-rs = { version = "3.3.7", features = ["static"] }
jsonld = { workspace = true, features = ["reqwest"] }
jstrict = "0.13.0"
log = "0.4.33"
mediatype = "0.22.0"
rdfx = "0.23.2"
stderrlog = "0.6.0"
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "net", "macros"] }

[lints]
workspace = true
