[package]
name = "jsonld-compaction"
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "JSON-LD document compaction implementation"
documentation = "https://docs.rs/jsonld-compaction"
readme = "README.md"

[features]
default = ["fast-hash"]
fast-hash = [
    "iri-rs/fast-hash",
    "jsonld-core/fast-hash",
    "jsonld-syntax/fast-hash",
    "jsonld-context-processing/fast-hash",
]

[dependencies]
contextual = "0.1.6"
educe = "0.6.0"
futures = "0.3.32"
indexmap = "2.14.0"
iri-rs = "3.3.4"
jsonld-context-processing.workspace = true
jsonld-core.workspace = true
jsonld-expansion.workspace = true
jsonld-syntax.workspace = true
jstrict = { git = "ssh://git@github.com/mskvarc/jstrict.git" }
langtag = "1.1.0"
mown = "1.0.0"
rdf-rs = { git = "ssh://git@github.com/mskvarc/rdf-rs.git" }
smallvec = "1.15.1"
thiserror = "2.0.18"
