[package]
name = "jsonld-compaction"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "JSON-LD document compaction implementation"
documentation = "https://docs.rs/jsonld-compaction"
readme.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["fast-hash"]
fast-hash = [
    "jsonld-core/fast-hash",
    "jsonld-syntax/fast-hash",
    "jsonld-context-processing/fast-hash",
]

[dependencies]
contextual = "0.1.6"
jsonld-context-processing.workspace = true
jsonld-core.workspace = true
jsonld-expansion.workspace = true
jsonld-syntax.workspace = true
jstrict = "0.13.0"
mown = "1.0.0"
rdfx = "0.23.2"
smallvec = "1.15.2"
thiserror = "2.0.19"

[lints]
workspace = true
