[package]
name = "jsonld-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "JSON-LD syntax"
documentation = "https://docs.rs/jsonld-syntax"
readme.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["fast-hash"]
fast-hash = ["iri-rs/fast-hash"]
serde = [
    "dep:serde",
    "iri-rs/serde",
    "locspan/serde",
    "jstrict/serde",
    "indexmap/serde",
]
serde-json = ["jstrict/serde_json"]
ahash = ["dep:ahash"]
gxhash = ["dep:gxhash"]

[dependencies]
ahash = { version = "0.8", optional = true }
contextual = "0.1.6"
decoded-char = "0.1.1"
educe = "0.6.0"
gxhash = { version = "3", optional = true }
hashbrown = "0.17.0"
indexmap = "2.14.0"
iri-rs = "3.3.6"
jstrict = "0.13.0"
langtag = "1.1.0"
lasso = { version = "0.7", features = [
    "multi-threaded",
    "inline-more",
    "ahasher",
] }
locspan = "0.8.2"
rdfx = "0.23.2"
serde = { version = "1.0.228", features = ["derive"], optional = true }
smallvec = "1.15.1"
thiserror = "2.0.18"

[lints]
workspace = true
