[package]
name = "jsonld-syntax"
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "JSON-LD syntax"
documentation = "https://docs.rs/jsonld-syntax"
readme = "README.md"

[features]
serde = [
    "dep:serde",
    "iref/serde",
    "locspan/serde",
    "json-syntax/serde",
    "indexmap/serde",
]

[dependencies]
contextual = "0.1.6"
decoded-char = "0.1.1"
educe = "0.6.0"
hashbrown = "0.17.0"
indexmap = "2.14.0"
iref = "3.2.2"
json-syntax = "0.12.5"
langtag = "0.4.0"
locspan = "0.8.2"
rdf-types = "0.22.5"
serde = { version = "1.0.228", features = ["derive"], optional = true }
smallvec = "1.15.1"
thiserror = "2.0.18"
