[workspace]
members = [
    "jsonld",
    "jsonld-cli",
    "jsonld-compaction",
    "jsonld-context-processing",
    "jsonld-core",
    "jsonld-expansion",
    "jsonld-serialization",
    "jsonld-syntax",
    "jsonld-testing",
]
resolver = "3"

[workspace.package]
version = "0.22.0"
edition = "2024"
rust-version = "1.85.0"
authors = [
    "Timothée Haudebourg <author@haudebourg.net>",
    "Matej Škvarč <matej.skvarc@senlab.io>",
]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/mskvarc/jsonld/"
keywords = ["json-ld", "json", "semantic-web", "linked-data", "rdf"]
categories = ["web-programming", "database", "data-structures"]

[workspace.dependencies]
jsonld = { path = "jsonld", version = "0.22.0" }
jsonld-compaction = { path = "jsonld-compaction", version = "0.22.0" }
jsonld-context-processing = { path = "jsonld-context-processing", version = "0.22.0" }
jsonld-core = { path = "jsonld-core", version = "0.22.0" }
jsonld-expansion = { path = "jsonld-expansion", version = "0.22.0" }
jsonld-serialization = { path = "jsonld-serialization", version = "0.22.0" }
jsonld-syntax = { path = "jsonld-syntax", version = "0.22.0" }
jsonld-testing = { path = "jsonld-testing", version = "0.22.0" }
