[package]
name = "jsonld-context-processing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "JSON-LD context processing implementation"
documentation = "https://docs.rs/jsonld-context-processing"
readme.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["bytewise-iri"]
bytewise-iri = [
    "iri-rs/fast-hash",
    "jsonld-core/bytewise-iri",
    "jsonld-syntax/bytewise-iri",
]

[dependencies]
contextual = "0.1.6"
foldhash = "0.2.0"
iri-rs = "3.3.7"
jsonld-core.workspace = true
jsonld-syntax.workspace = true
parking_lot = "0.12.5"
rdfx = "0.24.0"
thiserror = "2.0.19"

[lints]
workspace = true
