[package]
name = "jsonld-context-processing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "JSON-LD context processing implementation"
documentation = "https://docs.rs/jsonld-context-processing"
readme.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["fast-hash"]
fast-hash = [
    "iri-rs/fast-hash",
    "jsonld-core/fast-hash",
    "jsonld-syntax/fast-hash",
]

[dependencies]
contextual = "0.1.6"
foldhash = "0.2.0"
futures = "0.3.32"
iri-rs = "3.3.5"
jsonld-core.workspace = true
jsonld-syntax.workspace = true
mown = "1.0.0"
parking_lot = "0.12.5"
rdfx = "0.23.2"
thiserror = "2.0.18"

[lints]
workspace = true
