[package]
name = "jsonld-expansion"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "JSON-LD document expansion implementation"
documentation = "https://docs.rs/jsonld-expansion"
readme.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["fast-hash"]
fast-hash = [
    "iri-rs/fast-hash",
    "jsonld-core/fast-hash",
    "jsonld-syntax/fast-hash",
    "jsonld-context-processing/fast-hash",
]
parallel = ["jsonld-core/parallel"]

[dependencies]
contextual = "0.1.6"
educe = "0.6.0"
futures = "0.3.32"
indexmap = "2.14.0"
iri-rs = "3.3.4"
jsonld-context-processing.workspace = true
jsonld-core.workspace = true
jsonld-syntax.workspace = true
jstrict = "0.13.0"
langtag = "1.1.0"
mown = "1.0.0"
rdfx = "0.23.1"
smallvec = "1.15.1"
thiserror = "2.0.18"

[dev-dependencies]
async-std = { version = "1.13.2", features = ["attributes"] }
jsonld.workspace = true
iri-rs = { version = "3.3.4", features = ["static"] }

[lints]
workspace = true
