[package]
name = "jsonld-testing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "Testing library for the `jsonld` library"
readme.workspace = true

[package.metadata.docs.rs]
all-features = true

[lib]
proc-macro = true

[dependencies]
contextual = "0.1.6"
iri-rs = { version = "3.3.7", features = ["static", "enum"] }
jsonld.workspace = true
proc-macro2 = "1.0.107"
quote = "1.0.47"
rdfx = { version = "0.23.2", features = ["contextual"] }
syn = { version = "3.0.3", features = ["full"] }
tokio = { version = "1.53.1", features = ["rt"] }
yansi = "1.0.1"
