[package]
name = "jsonld-testing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "Testing library for the `jsonld` library"
readme.workspace = true

[package.metadata.docs.rs]
all-features = true

[lib]
proc-macro = true

[dependencies]
async-std = "1.13.2"
contextual = "0.1.6"
iri-rs = { version = "3.3.5", features = ["static", "enum"] }
jsonld.workspace = true
litrs = "1.0.0"
proc-macro2 = "1.0.106"
proc-macro-error = "1.0.4"
quote = "1.0.45"
rdfx = { version = "0.23.2", features = [
    "contextual",
] }
syn = { version = "2.0.117", features = ["full"] }
yansi = "1.0.1"
