[package]
name = "jsonld-testing"
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "Testing library for the `jsonld` library"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
async-std = "1.13.2"
contextual = "0.1.6"
iri-rs = { version = "3.3.2", features = ["static", "enum"] }
jsonld.workspace = true
litrs = "1.0.0"
proc-macro2 = "1.0.106"
proc-macro-error = "1.0.4"
quote = "1.0.45"
rdf-rs = { git = "ssh://git@github.com/mskvarc/rdf-rs.git", features = [
    "contextual",
] }
syn = { version = "2.0.117", features = ["full"] }
yansi = "1.0.1"
