[package]
name = "jsonld"
edition.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
description = "JSON-LD implementation"
readme.workspace = true

[features]
default = ["fast-hash"]
fast-hash = [
    "iri-rs/fast-hash",
    "jsonld-core/fast-hash",
    "jsonld-syntax/fast-hash",
    "jsonld-context-processing/fast-hash",
    "jsonld-expansion/fast-hash",
    "jsonld-compaction/fast-hash",
    "jsonld-serialization/fast-hash",
]
reqwest = ["jsonld-core/reqwest"]
serde = ["jsonld-syntax/serde", "jsonld-core/serde"]
serde-json = ["jsonld-syntax/serde-json", "jsonld-core/serde-json"]
ahash = ["jsonld-core/ahash"]
gxhash = ["jsonld-core/gxhash"]
parallel = [
    "jsonld-core/parallel",
    "jsonld-expansion/parallel",
    "jsonld-compaction/parallel",
]
expandable = ["dep:jsonld-expandable", "dep:jsonld-expandable-core"]
expandable-serde-json = ["expandable", "jsonld-expandable-core/serde-json"]
expandable-sonic-rs = ["expandable", "jsonld-expandable-core/sonic-rs"]
expandable-jstrict = ["expandable", "jsonld-expandable-core/jstrict"]
expandable-chrono = ["expandable", "jsonld-expandable-core/chrono"]
vocab = ["dep:jsonld-vocab", "iri-rs/static"]

[dependencies]
contextual = "0.1.6"
futures = "0.3.32"
iri-rs = "3.3.4"
jsonld-compaction.workspace = true
jsonld-context-processing.workspace = true
jsonld-core.workspace = true
jsonld-expandable = { workspace = true, optional = true }
jsonld-expandable-core = { workspace = true, optional = true }
jsonld-expansion.workspace = true
jsonld-serialization.workspace = true
jsonld-syntax.workspace = true
jsonld-vocab = { workspace = true, optional = true }
jstrict = "0.13.0"
locspan = "0.8.2"
rdfx = "0.23.1"
thiserror = "2.0.18"

[dev-dependencies]
async-std = { version = "1.13.2", features = ["attributes"] }
criterion = "0.8.2"
serde_json = "1.0"
iri-rs = { version = "3.3.4", features = ["static"] }
jsonld-testing.workspace = true
log = "0.4.29"
mimalloc = { version = "0.1", default-features = false }
n-quads = "0.20.0"
stacker = "0.1.24"

[[bench]]
name = "expansion"
harness = false

[[bench]]
name = "compaction"
harness = false

[[example]]
name = "profile"
path = "examples/profile.rs"

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
