[package]
name = "jsonld"
edition.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
description = "JSON-LD implementation"
readme = "README.md"

[features]
reqwest = ["jsonld-core/reqwest"]
serde = ["jsonld-syntax/serde", "jsonld-core/serde"]
ahash = ["jsonld-core/ahash"]
gxhash = ["jsonld-core/gxhash"]

[dependencies]
contextual = "0.1.6"
futures = "0.3.32"
iri-rs = "3.3.3"
json-syntax = "0.12.5"
jsonld-compaction.workspace = true
jsonld-context-processing.workspace = true
jsonld-core.workspace = true
jsonld-expansion.workspace = true
jsonld-serialization.workspace = true
jsonld-syntax.workspace = true
locspan = "0.8.2"
rdf-rs = { git = "ssh://git@github.com/mskvarc/rdf-rs.git" }
thiserror = "2.0.18"

[dev-dependencies]
async-std = { version = "1.13.2", features = ["attributes"] }
criterion = "0.8.2"
iri-rs = { version = "3.3.3", features = ["static"] }
jsonld-testing.workspace = true
log = "0.4.29"
n-quads = { git = "ssh://git@github.com/mskvarc/n-quads.git" }
stacker = "0.1.24"

[[bench]]
name = "expansion"
harness = false

[[bench]]
name = "compaction"
harness = false

[package.metadata.docs.rs]
all-features = true
