//! Runtime support for the JSON-LD `Expandable` derive macro.
//!
//! This crate hosts:
//!
//! - The [`Expandable`] trait that the derive macro implements.
//! - The [`JsonValue`] backend trait abstracting any JSON value type the
//!   derive can emit (`serde_json::Value`, `sonic_rs::Value`,
//!   `jstrict::Value`, or a user-supplied type).
//! - The [`ToJsonValue`] trait used by generated code to convert leaf field
//!   values into a chosen [`JsonValue`] backend.
//! - The attribute parser, intermediate representation, and codegen used by
//!   the `jsonld-expandable` proc-macro crate (kept here so it can be
//!   unit-tested without `trybuild`).
//!
//! Application code rarely depends on this crate directly; instead enable a
//! `expandable*` feature on the umbrella `jsonld` crate.

pub mod attrs;
pub mod codegen;
pub mod ir;
pub mod iri;

mod value;

#[cfg(any(feature = "serde_json", feature = "sonic_rs", feature = "jstrict"))]
mod backends;

pub use value::{JsonValue, ToJsonValue};

/// Convert `&self` into the expanded JSON-LD form for the chosen backend `V`.
///
/// Generated by the `Expandable` derive in `jsonld-expandable`.
pub trait Expandable {
    /// Render `self` as expanded JSON-LD using backend `V`.
    fn expand<V: JsonValue>(&self) -> V;
}

/// Field marker for dynamic `@type` arrays.
///
/// Implement this for fields tagged with `#[jsonld(type_value)]` to provide a
/// `@type` array whose contents are computed at runtime.
pub trait ExpandableTypeValue {
    fn to_type_array<V: JsonValue>(&self) -> V;
}

/// Field marker for `@container: @language` maps backed by user-defined types.
///
/// `HashMap<String, T>` automatically routes through the built-in language-map
/// codegen path; implement this when you need a custom type to participate.
pub trait ExpandableLanguageMap {
    fn to_expanded_language_map<V: JsonValue>(&self) -> V;
}

/// Driver entry used by the proc-macro shell crate.
///
/// Lives here so the parser, IR, and codegen can be exercised by ordinary
/// `#[test]` functions; proc-macro crates cannot host normal tests.
pub fn derive_expandable(input: syn::DeriveInput) -> proc_macro2::TokenStream {
    match codegen::generate(&input) {
        Ok(ts) => ts,
        Err(err) => err.to_compile_error(),
    }
}
