[package]
name = "jsonld-serialization"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true
description = "JSON-LD serialization"
documentation = "https://docs.rs/jsonld-serialization"
readme.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["fast-hash"]
fast-hash = ["iri-rs/fast-hash", "jsonld-core/fast-hash"]

[dependencies]
iri-rs = "3.3.7"
jsonld-core.workspace = true
jstrict = "0.14.0"
ld-core = "0.4.0"
rdfx = "0.24.0"
thiserror = "2.0.19"
xsd-rs = "0.10.0"

[dev-dependencies]
contextual = "0.1.6"
jstrict = "0.14.0"
ld-core = { version = "0.4.0", features = ["derive"] }

[lints]
workspace = true
